name: shop_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  fluttertoast: ^7.1.1
  firebase_core: "^0.5.2+1"
  cloud_firestore: ^0.14.3+1
  firebase_storage: ^5.1.0
  flutter_image_compress: ^0.7.0
  firebase_auth: ^0.18.3+1
  camera:
  image_picker: ^0.6.7+14
  path_provider:
  path:
dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:


  uses-material-design: true


  assets:
      - assets/images/google.jpg
      - assets/images/gmail.jpg


  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-ExtraLight.ttf

          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
